### ISSUE TITLE
Disabling DEBUG in settings.py removes HTML formatting

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/InventoryManagement#21]
In settings.py DEBUG is turned on. It is recommended for production environments to turn it off.

However, do this and the HTML UI breaks - this doomed #14 

@Greg-Hawkridge says the answer is to use whitenoise to make the staticfiles available. Tell us more and make a PR :)

**Comment by anandarupmukherjee** [comment]
Recommended...not mandatory. I have no experience in deploying a production version. Will need to fall-back on greg's expertise.

**Comment by tobyaharris** [comment]
^ manually added to tracker

**Comment by tobyaharris** [comment]
Look in job tracking for an example. Include whitenoise in apps list. Pip install via requirements.txt.

**Comment by tobyaharris** [comment]
Upon searching through job tracking for `whitenoise`:

`user_input_dc/code/requirements.txt` :
```
whitenoise==5.1.0
```

`location_sds/code/job_locations/settings.py` :
```
INSTALLED_APPS = [
    ...
    'whitenoise',
    ...
```


`user_input_dc/code/site_config/settings.py`  and `location_sds/code/job_locations/settings.py` and `dashboard_ui/code/management_portal/settings.py` : 
```
MIDDLEWARE = [
    ...
    'whitenoise.middleware.WhiteNoiseMiddleware',
    ...
```

Which raises 2 questions for me:
1. Why is whitenoise included in the pip requirements for only 1 of the 3 docker containers / service modules it is used in? Doesn't it need to be installed separately into each?
2. Why is whitenoise only included in the `INSTALLED_APPS` list in a different 1 of the 3 docker containers / service modules? Why does it not need to be included in all 3?

**Comment by tobyaharris** [comment]
See [the `bugfix/whitenoise` branch](https://github.com/DigitalShoestringSolutions/InventoryManagement/tree/bugfix/whitenoise)
