### ISSUE TITLE
Spelling locale: s or z

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/InventoryManagement#25]
There's a spelling decision to be made (but not quite #23 ).

Do we have a policy on en-GB / en-US? 
Hedging bets has funny consequences like:

https://github.com/DigitalShoestringSolutions/Inventory_management/blob/c900f8137fec70fe77741dc13bb8a5f819f136ac/inventory_app/templates/inventory_app/home.html#L73-L75

**Comment by anandarupmukherjee** [comment]
That is just really bad coding practice on my part...and doing things piecewise at different times. Will be careful in the future.

**Comment by tobyaharris** [comment]
np. But this issue is not closed until a PR has been merged that corrects this everywhere.
