### ISSUE TITLE
Homepage search by all columns

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/InventoryManagement#26]
On the homepage, there is a table of stock status. It's nice that it has an option to search/filter by item and location. 

Could the search capability be extended to all the other fields? For example, if I'm desperately serching for something that is stocked in many locations but has run out in most, it might be nice to search by `Available` > 0. 

These search boxes also can't be used simultaneously. If I begin to type in one field which narrows down the entries, when I click in the other field the effect of the first filter is removed. The text remains in the first box. If I tab back to the first search field, it become effective again but the second field is no longer applied to the serch. 

Also, I do not see the value of displaying the `ID` column - is that something that django insisted on?

**Comment by anandarupmukherjee** [comment]
yes, it can be. However, the core shoestring idea is not to overdo things; rather provide a workable, quickly developed, and rapidly deployable solution.
