### ISSUE TITLE
Popups everywhere

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/InventoryManagement#28]
When using the UI, there's a lot of popups to contend with. 
I imagine a user will get fustrated at these within minutes of setting the system up. 

Popups are raised that require a click to dismiss when:
eg:
- Consolidating stock (confirming receipt of an order)
- Placing an order
- Submitting a withdrawal
- Submitting the contents of each location's stock check (`feature/stock-check-only`)

Can some of these be suppressed? Could the message appear elsewhere on the screen without interferring with continued interaction?

**Comment by anandarupmukherjee** [comment]
It was requested by trandos during one of their initial feedbacks. Anyways, good to have annoying alerts notifying you of your actions (just to be sure).
