### ISSUE TITLE
Date format: dd/mm/yyyy vs mm/dd/yyyy

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/InventoryManagement#32]
Currently in the Order Stock page the data is formatted month first. Much like #25 , unless there is specific demand for month first can we default to the UK/AUS standard for dd/mm/yyyy?

**Comment by tobyaharris** [comment]
manually adding to tracker project

**Comment by Greg-Hawkridge** [comment]
Only seems to do this for Toby. Not observed on Anand's mac during the meeting. (what branch/version was this?)

**Comment by tobyaharris** [comment]
Investigate possible causes of this. Is it client machine specific? Is it in pi setup? Add screenshots of where it does and doesn't happen.

**Comment by anandarupmukherjee** [comment]
seems like a non-issue
